language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    - rm -rf public
    - hugo
env:
    global:
        - GITHUB_REF: github.com/ld000/blog-hugo.git
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master