language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    - rm -rf public
    - hugo
after_success:
    - git config user.name "ld000"
    - git config user.email "lidong9144@163.com"
    - cd public && git add --all && git commit -m "update public" && git push "https://${GITHUB_TOKEN}@${GITHUB_REF}" master && cd ..
    - git subtree push --prefix public "https://${GITHUB_TOKEN}@${GITHUB_REF}" gh-pages
env:
    global:
        - GITHUB_REF: github.com/ld000/blog-hugo.git